import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#615e5a",
        "surface-bright": "#FFF8EA",
        "surface-dim": "#e0d9cb",
        "on-tertiary-fixed-variant": "#55414a",
        "secondary-fixed-dim": "#c0cbae",
        surface: "#F7F3EA",
        primary: "#000000",
        "primary-container": "#1d1b18",
        "on-secondary": "#ffffff",
        "outline-variant": "#cdc5bc",
        "inverse-on-surface": "#f7f0e2",
        "surface-variant": "#e9e2d4",
        "primary-fixed-dim": "#cbc5c0",
        "surface-container": "#f4eddf",
        "primary-fixed": "#e8e1dc",
        "error-container": "#ffdad6",
        background: "#F7F3EA",
        "tertiary-container": "#27171f",
        "on-error": "#ffffff",
        outline: "#7c766e",
        "inverse-primary": "#cbc5c0",
        "on-surface": "#1e1b13",
        secondary: "#58624a",
        "on-primary-fixed": "#1d1b18",
        "surface-container-low": "#faf3e4",
        "on-secondary-container": "#5e6850",
        error: "#ba1a1a",
        "on-secondary-fixed": "#161e0c",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#dbbfca",
        tertiary: "#000000",
        "on-secondary-fixed-variant": "#404a34",
        "surface-container-lowest": "#FFFCF5",
        "inverse-surface": "#333027",
        "on-background": "#1e1b13",
        "on-surface-variant": "#4b463f",
        "on-primary-fixed-variant": "#494642",
        "secondary-container": "#dce7c9",
        "surface-container-high": "#efe7d9",
        "on-primary-container": "#88837e",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#dce7c9",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#967d87",
        "surface-container-highest": "#e9e2d4",
        "tertiary-fixed": "#f8dbe6",
        "on-tertiary-fixed": "#27171f",
        sage: "#CAD5B8",
        "warm-white": "#FFFDF8",
        "warm-gray": "#E5DED0",
        "near-black": "#171511",
        "cream-bg": "#F7F3EA",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "40px",
        sm: "12px",
        lg: "48px",
        gutter: "24px",
        md: "24px",
        xl: "80px",
        "max-width": "1280px",
        "margin-mobile": "16px",
        xs: "4px",
        base: "8px",
      },
      fontFamily: {
        "display-lg-mobile": ["Playfair Display"],
        "headline-sm": ["Playfair Display"],
        "label-md": ["Plus Jakarta Sans"],
        "display-lg": ["Playfair Display"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "title-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Playfair Display"],
      },
      fontSize: {
        "display-lg-mobile": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "headline-sm": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "label-md": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.04em",
            fontWeight: "600",
          },
        ],
        "display-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-lg": [
          "16px",
          { lineHeight: "26px", fontWeight: "400" },
        ],
        "label-sm": [
          "11px",
          { lineHeight: "14px", fontWeight: "500" },
        ],
        "body-md": [
          "14px",
          { lineHeight: "22px", fontWeight: "400" },
        ],
        "title-lg": [
          "18px",
          { lineHeight: "24px", fontWeight: "600" },
        ],
        "headline-md": [
          "32px",
          { lineHeight: "40px", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
