/**
 * InsightPM AI Batch Runner
 * 运行: npx tsx scripts/batch-run.ts --cases onboarding-activation-v1,onboarding-activation-v2 --count 150 --stage hard
 *
 * 批量执行 pipeline，生成 batch summary。
 */

import * as fs from "fs";
import * as path from "path";
import { execSync } from "child_process";

const PROJECT_ROOT = path.join(__dirname, "..");
const RUNS_DIR = path.join(PROJECT_ROOT, "runs");

interface BatchConfig {
  cases: string[];
  count: number;
  stage: "hard" | "semantic" | "full";
  skipSemantic: boolean;
  resume: boolean;
  concurrency: number;
  baseline: string;
}

interface CaseResult {
  caseName: string;
  status: "pass" | "fail" | "warning" | "skipped";
  durationMs: number;
  hardValidationStatus: string;
  hardValidationScore: number;
  semanticStatus: string;
  semanticScore: number;
  criticalIssues: number;
  evidenceBroken: number;
  promoted: boolean;
  slowSteps: string[];
  error?: string;
}

interface BatchSummary {
  startedAt: string;
  finishedAt: string;
  durationMs: number;
  totalCases: number;
  passCases: number;
  warningCases: number;
  failCases: number;
  skippedCases: number;
  cases: CaseResult[];
}

function parseArgs(): BatchConfig {
  const args = process.argv.slice(2);
  let cases: string[] = [];
  let count = 150;
  let stage: "hard" | "semantic" | "full" = "full";
  let skipSemantic = false;
  let resume = false;
  let concurrency = 1;
  let baseline = "";

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--cases" && args[i + 1]) cases = args[++i].split(",");
    if (args[i] === "--count" && args[i + 1]) count = parseInt(args[++i], 10);
    if (args[i] === "--stage" && args[i + 1]) stage = args[++i] as any;
    if (args[i] === "--skip-semantic") skipSemantic = true;
    if (args[i] === "--resume") resume = true;
    if (args[i] === "--concurrency" && args[i + 1]) concurrency = parseInt(args[++i], 10);
    if (args[i] === "--baseline" && args[i + 1]) baseline = args[++i];
  }

  return { cases, count, stage, skipSemantic, resume, concurrency, baseline };
}

function loadRunSummary(caseName: string): any {
  const summaryPath = path.join(RUNS_DIR, caseName, "run-summary.json");
  return fs.existsSync(summaryPath) ? JSON.parse(fs.readFileSync(summaryPath, "utf-8")) : null;
}

function generateMarkdown(summary: BatchSummary): string {
  const lines: string[] = [];
  lines.push("# Batch Run Summary");
  lines.push("");
  lines.push(`**Started:** ${summary.startedAt}`);
  lines.push(`**Finished:** ${summary.finishedAt}`);
  lines.push(`**Duration:** ${(summary.durationMs / 1000).toFixed(1)}s`);
  lines.push(`**Total:** ${summary.totalCases} | **Pass:** ${summary.passCases} | **Warning:** ${summary.warningCases} | **Fail:** ${summary.failCases} | **Skipped:** ${summary.skippedCases}`);
  lines.push("");
  lines.push("| Case | Status | Duration | Hard | Semantic | Critical | Evidence Broken | Promoted | Slow Steps |");
  lines.push("| --- | --- | --- | --- | --- | --- | --- | --- | --- |");

  for (const c of summary.cases) {
    const dur = c.durationMs > 0 ? `${(c.durationMs / 1000).toFixed(1)}s` : "-";
    const hard = c.hardValidationStatus ? `${c.hardValidationStatus} (${c.hardValidationScore}/100)` : "-";
    const sem = c.semanticStatus ? `${c.semanticStatus} (${c.semanticScore}/100)` : "-";
    const crit = c.criticalIssues ?? "-";
    const evid = c.evidenceBroken ?? "-";
    const promoted = c.promoted ? "YES" : "no";
    const slow = c.slowSteps.length > 0 ? c.slowSteps.join(", ") : "-";
    const statusIcon = c.status === "pass" ? "PASS" : c.status === "warning" ? "WARN" : c.status === "fail" ? "FAIL" : "SKIP";
    lines.push(`| ${c.caseName} | ${statusIcon} | ${dur} | ${hard} | ${sem} | ${crit} | ${evid} | ${promoted} | ${slow} |`);
  }

  lines.push("");
  lines.push("---");
  lines.push("*Auto-generated by `npm run insightpm:batch-run`*");
  return lines.join("\n");
}

async function main() {
  const config = parseArgs();

  if (config.cases.length === 0) {
    console.error("Usage: tsx scripts/batch-run.ts --cases case1,case2,case3 [--count 150] [--stage hard|semantic|full]");
    process.exit(1);
  }

  const startedAt = new Date().toISOString();
  const startMs = Date.now();
  const caseResults: CaseResult[] = [];

  console.log("=".repeat(60));
  console.log(`InsightPM Batch Run`);
  console.log(`  Cases: ${config.cases.length}`);
  console.log(`  Count: ${config.count}`);
  console.log(`  Stage: ${config.stage}`);
  console.log(`  Resume: ${config.resume}`);
  console.log(`  Concurrency: ${config.concurrency}`);
  console.log("=".repeat(60));
  console.log("");

  for (let i = 0; i < config.cases.length; i++) {
    const caseName = config.cases[i];
    const caseStartMs = Date.now();

    console.log(`[${i + 1}/${config.cases.length}] ${caseName}`);
    console.log("-".repeat(40));

    // Derive baseline from caseName if not specified
    const baseline = config.baseline || caseName;

    // Build command
    const cmdParts = [
      `npx tsx scripts/run-pipeline.ts`,
      `--case ${caseName}`,
      `--count ${config.count}`,
      `--baseline ${baseline}`,
      `--stage ${config.stage}`,
    ];
    if (config.skipSemantic) cmdParts.push("--skip-semantic");
    if (config.resume) cmdParts.push("--resume");

    try {
      execSync(cmdParts.join(" "), {
        cwd: PROJECT_ROOT,
        stdio: "inherit",
        timeout: 600000, // 10 min timeout per case
      });

      // Read run summary
      const runSummary = loadRunSummary(caseName);
      const caseDurationMs = Date.now() - caseStartMs;

      caseResults.push({
        caseName,
        status: runSummary?.status || "pass",
        durationMs: caseDurationMs,
        hardValidationStatus: runSummary?.hardValidation?.status || "",
        hardValidationScore: runSummary?.hardValidation?.score || 0,
        semanticStatus: runSummary?.semanticValidation?.status || "",
        semanticScore: runSummary?.semanticValidation?.score || 0,
        criticalIssues: runSummary?.semanticValidation?.criticalIssues || 0,
        evidenceBroken: runSummary?.semanticValidation?.evidenceBroken || 0,
        promoted: runSummary?.promoted || false,
        slowSteps: runSummary?.slowSteps || [],
      });
    } catch (error) {
      const caseDurationMs = Date.now() - caseStartMs;
      const msg = error instanceof Error ? error.message : "Unknown error";

      caseResults.push({
        caseName,
        status: "fail",
        durationMs: caseDurationMs,
        hardValidationStatus: "",
        hardValidationScore: 0,
        semanticStatus: "",
        semanticScore: 0,
        criticalIssues: 0,
        evidenceBroken: 0,
        promoted: false,
        slowSteps: [],
        error: msg,
      });
    }

    console.log("");
  }

  const finishedAt = new Date().toISOString();
  const durationMs = new Date(finishedAt).getTime() - new Date(startedAt).getTime();

  const summary: BatchSummary = {
    startedAt,
    finishedAt,
    durationMs,
    totalCases: caseResults.length,
    passCases: caseResults.filter(c => c.status === "pass").length,
    warningCases: caseResults.filter(c => c.status === "warning").length,
    failCases: caseResults.filter(c => c.status === "fail").length,
    skippedCases: caseResults.filter(c => c.status === "skipped").length,
    cases: caseResults,
  };

  // Save outputs
  const batchDir = path.join(RUNS_DIR, "batch-run");
  fs.mkdirSync(batchDir, { recursive: true });

  const jsonPath = path.join(batchDir, "batch-run-summary.json");
  fs.writeFileSync(jsonPath, JSON.stringify(summary, null, 2), "utf-8");

  const mdPath = path.join(batchDir, "batch-run-summary.md");
  fs.writeFileSync(mdPath, generateMarkdown(summary), "utf-8");

  // Print summary
  console.log("=".repeat(60));
  console.log(`Batch Run Complete`);
  console.log("=".repeat(60));
  console.log(`  Duration: ${(durationMs / 1000).toFixed(1)}s`);
  console.log(`  Total: ${summary.totalCases}`);
  console.log(`  Pass: ${summary.passCases}`);
  console.log(`  Warning: ${summary.warningCases}`);
  console.log(`  Fail: ${summary.failCases}`);
  console.log(`  Output: ${jsonPath}`);
  console.log("");

  if (summary.failCases > 0) process.exit(1);
}

main().catch((error) => {
  console.error("Batch run failed:", error);
  process.exit(1);
});
