/**
 * 统一中文文案常量 — ProofLoop 前端
 * 所有用户可见 UI 文案集中管理，组件直接引用。
 */

export const COPY = {
  /* ── Sidebar ── */
  sidebar: {
    brand: "AI 反馈分析引擎",
    demoMode: "演示模式",
  },

  /* ── Layout ── */
  layout: {
    title: "ProofLoop - AI 反馈分析引擎",
  },

  /* ── Dashboard ── */
  dashboard: {
    searchPlaceholder: "搜索分析、运行记录或报告...",
    heroTitle: "把用户反馈变成可信产品洞察",
    heroDesc: "上传原始用户反馈，自动生成结构化产品分析报告，并通过硬性校验 Hard Validation、语义评分和证据链追踪验证每一个结论。",
    newAnalysis: "新建分析",
    viewDemo: "查看演示",
    metrics: {
      acceptedDatasets: "已采纳数据集",
      trainingFeedbacks: "训练反馈量",
      hardValidation: "硬性校验",
      semanticScore: "语义评分",
      evidenceBroken: "证据断裂",
      ciSmoke: "CI 冒烟测试",
    },
    latestAnalysis: "最新分析",
    viewDetails: "查看详情",
    hardVal: "硬性校验",
    semantic: "语义评分",
    evidenceBroken: "证据断裂",
    duration: "耗时",
    validationChecks: "校验检查",
    hardValidation: "硬性校验 Hard Validation",
    hardValidationDesc: "精确匹配与结构完整性已验证。",
    semanticValidation: "语义校验 Semantic Validation",
    semanticValidationDesc: "语义对齐度与源数据高度一致。",
    consistencyGuard: "一致性守卫",
    consistencyGuardDesc: "未检测到跨分组矛盾洞察。",
    regressionTest: "回归测试",
    regressionTestDesc: "等待历史对比运行。",
    processingFlow: "处理流程",
    flowSteps: {
      rawCsv: "原始 CSV",
      normalizedJson: "标准化 JSON",
      segments: "分组",
      analysisJson: "分析 JSON",
      markdownReport: "Markdown 报告",
      validation: "校验",
      acceptedDataset: "已采纳数据集",
    },
    recentRuns: "最近运行",
    viewAll: "查看全部",
    table: {
      caseName: "案例名称",
      scenario: "场景",
      feedbackCount: "反馈数",
      hardScore: "硬性校验",
      semanticScore: "语义评分",
      status: "状态",
    },
  },

  /* ── Runs ── */
  runs: {
    title: "运行历史",
    subtitle: "查看并管理历史 AI 分析执行记录。",
    runNewAnalysis: "新建分析",
    filterPlaceholder: "按案例名称筛选...",
    statusAll: "状态：全部",
    pass: "通过",
    fail: "失败",
    running: "运行中",
    scenarioAll: "场景：全部",
    table: {
      caseName: "案例名称",
      scenario: "场景",
      feedbackCount: "反馈数",
      hardScore: "硬性校验",
      semanticScore: "语义评分",
      status: "状态",
      duration: "耗时",
      actions: "操作",
    },
    viewReport: "查看报告",
  },

  /* ── Run Detail ── */
  runDetail: {
    hardScore: "硬性校验",
    semanticScore: "语义评分",
    criticalIssues: "关键问题",
    feedbackCount: "反馈数",
    hardValidation: "硬性校验 Hard Validation",
    check: "校验项",
    status: "状态",
    score: "得分",
    message: "信息",
    semanticValidation: "语义校验 Semantic Validation",
    scoreLabel: "得分",
    recommendations: "建议",
    evidenceTrace: "证据链 Evidence Trace",
    clusters: "个问题簇",
    clusterId: "问题簇 ID",
    feedbackCountLabel: "反馈数",
    evidenceIds: "证据 ID",
    match: "匹配",
    matched: "匹配",
    mismatched: "不匹配",
  },

  /* ── New Analysis ── */
  newAnalysis: {
    title: "新建分析任务",
    subtitle: "上传数据并配置您的 AI 分析流水线。",
    uploadData: "上传反馈数据",
    uploadDesc: "支持原始用户反馈 CSV 格式。",
    dragDrop: "拖拽 CSV 文件至此处，或点击浏览",
    maxSupport: "最大支持 50MB（仅限 .csv）",
    config: "运行配置",
    scenarioName: "分析场景",
    caseName: "案例名称",
    caseNameHint: "仅允许 a-z, 0-9, -, _",
    semanticModel: "语义模型",
    defaultTag: "默认",
    hardValidationRules: "硬性校验 Hard Validation 规则",
    minWordCount: "最少字数要求（>10）",
    filterPii: "过滤 PII（个人可识别信息）",
    strictJson: "严格 JSON 格式输出",
    uploading: "上传中...",
    uploadCsv: "上传 CSV",
    analyzing: "分析中...",
    startAnalysis: "开始分析",
  },

  /* ── Training Data ── */
  trainingData: {
    title: "训练数据",
    subtitle: "管理已通过验证的高质量反馈数据集。",
    searchPlaceholder: "搜索数据集...",
    uploadNew: "导入数据集",
    totalDatasets: "总数据集",
    accepted: "已采纳",
    pending: "待定",
    totalFeedback: "总反馈量",
    heldoutEvalSets: "预留评估集",
    datasetDirectory: "数据仓库",
    table: {
      datasetId: "数据集 ID",
      category: "场景",
      records: "反馈数量",
      qualityScore: "质量评分",
      lastUpdated: "最后更新",
      actions: "操作",
    },
    export: "导出",
  },

  /* ── Evaluation ── */
  evaluation: {
    title: "评估校验",
    subtitle: "对比不同模型的语义评分与硬性校验 Hard Validation 通过率。",
    searchPlaceholder: "搜索...",
    globalBenchmark: "全局基准评分",
    thisWeek: "+1.2% 本周",
    totalEvaluations: "总评估数",
    activeModels: "活跃模型",
    evaluationSets: "评估集",
    newEvaluation: "新建评估",
    table: {
      benchmarkName: "基准名称",
      model: "模型",
      semanticScore: "语义评分",
      hardPassRate: "硬性校验通过率",
      evidence: "证据",
      date: "日期",
    },
    errorDistribution: "错误分布",
    errorDistDesc: "全部模型（最近 7 天）",
    logicError: "逻辑错误",
    hallucination: "幻觉",
    formatError: "格式",
  },

  /* ── Settings ── */
  settings: {
    title: "系统设置",
    subtitle: "管理 AI 分析和存储的全局配置。",
    exportConfig: "导出配置",
    saveSettings: "保存设置",
    modelConfig: "模型配置",
    defaultSemanticModel: "默认语义模型",
    modelDesc: "选择用于语义解析的主模型。",
    semanticThreshold: "语义评分阈值",
    loose: "宽松 (0)",
    strict: "严格 (100)",
    executionGuard: "执行守卫",
    enableConsistency: "开启一致性守卫",
    consistencyDesc: "自动交叉验证分析结果与历史数据。",
    enableRegression: "开启回归测试",
    regressionDesc: "在生成最终报告前运行基线对比。",
    storageLimits: "存储与限制",
    maxUploadSize: "最大上传限制",
    maxUploadDesc: "训练数据上传允许的最大文件大小。",
    applySettings: "应用配置",
    discardChanges: "放弃修改",
  },

  /* ── Analysis Report ── */
  analysisReport: {
    searchPlaceholder: "搜索分析报告...",
    reportTitle: "分组分析报告：",
    exportPdf: "导出 PDF",
    generateInsight: "生成报告洞察",
    generating: "生成中...",
    switchReport: "切换报告：",
    metadata: {
      id: "ID",
      type: "类型",
      businessGoal: "业务目标",
      feedbackCount: "反馈数量",
      clusterCount: "聚类数量",
    },
    metrics: {
      feedback: "反馈数",
      segments: "分组数",
      clusters: "问题数",
      hardScore: "硬性校验",
      semanticScore: "语义评分",
      evidenceBroken: "证据断裂",
    },
    topProblems: "主要产品问题",
    problemCount: "个问题簇",
    impact: "影响",
    action: "建议",
    feedbackLabel: "反馈数",
    scoreLabel: "得分",
    evidenceComplete: "证据完整",
    needsValidation: "需验证",
    segmentOverview: "分层概览",
    evidencePreview: "证据追踪预览",
    table: {
      segment: "分组",
      totalFeedback: "反馈总数",
      p0Count: "P0 数量",
      status: "状态",
      cluster: "问题簇",
      evidenceExample: "证据 / 样例",
      trace: "追踪",
      problem: "问题",
      evidenceFeedbackIds: "证据反馈 ID",
      count: "数量",
      exampleFeedback: "反馈样例",
      traceStatus: "追踪状态",
    },
    valid: "有效",
    ignored: "已忽略",
    passed: "通过",
    needsManualReview: "需人工复核",
    records: "条记录",
    noProblemData: "该报告暂无可用问题数据。",
    noSegmentData: "该报告暂无可用分组分析数据。请确认 pipeline 已生成分组分析 JSON 和 Markdown。",
    generateSegInsight: "生成当前分组洞察",
    markdownTab: "完整分析报告 (Markdown)",
    copyCode: "复制代码",
    copy: "复制",
    copied: "已复制",
    downloadMd: "下载 .md",
    noMarkdown: "暂无 Markdown 报告。请先运行分析生成报告。",
    evidenceTraceTitle: "证据链路追踪",
    evidenceTraceDesc: "验证 AI 洞察与原始反馈数据的直接对应关系，确保分析结果的可追溯性。",
  },

  /* ── Downloads ── */
  downloads: {
    title: "分析产物下载",
    desc: "获取结构化数据或便于共享的文档格式。",
    overallMarkdown: "总体 Markdown 报告",
    overallMarkdownDesc: "完整分析报告 Markdown 格式",
    overallJson: "总体 JSON",
    overallJsonDesc: "完整分析结果结构化数据",
    segmentJson: "分组 JSON",
    segmentJsonDesc: "当前分组结构化分析数据",
    segmentMarkdown: "分组 Markdown",
    segmentMarkdownDesc: "当前分组 Markdown 报告",
    hardValidationJson: "硬性校验 Hard Validation JSON",
    hardValidationJsonDesc: "43 项硬性校验结果",
    semanticValidationJson: "语义校验 Semantic Validation JSON",
    semanticValidationJsonDesc: "语义一致性校验结果",
    validationSummary: "校验摘要",
    validationSummaryDesc: "校验结果汇总",
    evidenceChainCsv: "证据链 Evidence Trace CSV",
    evidenceChainCsvDesc: "证据链对照表",
    reportInsightJson: "报告洞察 JSON",
    reportInsightJsonDesc: "报告级执行洞察",
    allArtifactsZip: "全部产物 ZIP",
    allArtifactsZipDesc: "打包下载全部分析产物",
    download: "下载",
    downloadAll: "一键下载全部",
    selectSegment: "需选择分组",
  },

  /* ── Insight Modal ── */
  insight: {
    reportInsight: "报告级执行洞察",
    segmentInsight: "分组洞察",
    oneLineSummary: "一句话摘要",
    topProblems: "主要问题",
    p0Issues: "P0 高风险问题",
    crossSegmentPatterns: "跨分组模式",
    recommendedActions: "建议行动",
    riskWarnings: "严重风险提醒",
    validationSummary: "校验状态",
    hardLabel: "硬性校验",
    semanticLabel: "语义评分",
    evidenceBrokenLabel: "证据断裂",
    followUpQuestions: "需要进一步验证",
    topRisks: "主要风险",
    copyInsight: "复制洞察",
    downloadJson: "下载 JSON",
    copiedToClipboard: "已复制到剪贴板",
    close: "关闭",
  },

  /* ── Auth ── */
  auth: {
    login: "登录",
    signup: "注册",
    loginWorkspace: "登录工作台",
    enterDemoWorkspace: "进入 ProofLoop Demo Workspace",
    fullName: "姓名",
    workEmail: "工作邮箱",
    workspaceName: "工作区名称",
    password: "密码",
    confirmPassword: "确认密码",
    rememberMe: "记住我",
    forgotPassword: "忘记密码？",
    termsOfService: "服务条款",
    privacyPolicy: "隐私政策",
    useDemoAccess: "使用 Demo 访问码",
    noAccount: "还没有账号？",
    hasAccount: "已有账号？",
    createAccount: "创建账号",
    or: "或者",
    demoConsole: "Demo 控制台",
    localDemoMode: "本地演示模式",
    localDemoEnabled: "本地演示模式已启用",
    enterDemoAccessCode: "请输入您的 Demo 访问码",
    accessCode: "访问码",
    localNoCode: "本地环境无需访问码",
    localEnter: "本地环境直接进入",
    enterDemo: "进入 Demo",
    backToLogin: "返回登录",
    demoOnlyForTesting: "Demo 模式仅用于本地演示和内部测试。",
    saasNotice: "正式账号系统将在 SaaS 版本启用。",
    passwordResetNotice: "密码重置将在 SaaS 版本启用。",
    demoCodeIncorrect: "Demo 访问码不正确。",
    accountSystemNotice: "当前账号系统将在 SaaS 版本启用。",
  },

  /* ── Common ── */
  common: {
    pass: "通过",
    failed: "失败",
    pending: "等待中",
    running: "运行中",
    valid: "有效",
    ignored: "已忽略",
    complete: "已完成",
    incomplete: "未完成",
    success: "成功",
    error: "错误",
    warning: "警告",
    loading: "加载中",
    empty: "暂无数据",
    retry: "重试",
    save: "保存",
    cancel: "取消",
    apply: "应用",
    delete: "删除",
    edit: "编辑",
    create: "创建",
    update: "更新",
    back: "返回",
    next: "下一步",
    previous: "上一步",
    copy: "复制",
    copied: "已复制",
    download: "下载",
    export: "导出",
    search: "搜索",
  },
} as const;
